
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 
 * @author Admin
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Edit() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ins = new javax.swing.JButton();
        a = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        nr = new javax.swing.JTextField();
        textUser1 = new javax.swing.JLabel();
        textUser2 = new javax.swing.JLabel();
        textUser3 = new javax.swing.JLabel();
        textUser4 = new javax.swing.JLabel();
        textUser5 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 5));
        jPanel1.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 423));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 423));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setText("Înserare în BibliotecaVirtuală : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 460, 40));

        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titlu", "Autor", "Genul", "Editura", "Nr_carti", "Nr_carti_disponibile"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 590, 200));

        ins.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ins.setText("INSERT");
        ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insActionPerformed(evt);
            }
        });
        jPanel1.add(ins, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 110, -1));

        a.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 120, -1));

        g.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 120, -1));

        t.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, -1));

        nr.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 120, -1));

        textUser1.setBackground(new java.awt.Color(255, 255, 255));
        textUser1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        textUser1.setText("Autor");
        jPanel1.add(textUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 22));

        textUser2.setBackground(new java.awt.Color(255, 255, 255));
        textUser2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        textUser2.setText("Genul");
        jPanel1.add(textUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 22));

        textUser3.setBackground(new java.awt.Color(255, 255, 255));
        textUser3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        textUser3.setText("Nr_carti");
        jPanel1.add(textUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 130, 22));

        textUser4.setBackground(new java.awt.Color(255, 255, 255));
        textUser4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        textUser4.setText("Titlu");
        jPanel1.add(textUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 22));

        textUser5.setBackground(new java.awt.Color(255, 255, 255));
        textUser5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        textUser5.setText("Editura");
        jPanel1.add(textUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 130, 22));

        e.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, -1));

        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 110, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Biblioteca\\interior-biblioteca-sala-vacia-leer-libros-estantes-madera_33099-1722.jpg")); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        jLabel4.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 620, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showTableData(){
        try{
        Connection con=BDConn.getBDConn();
        PreparedStatement pst =con.prepareStatement("Select nume_carte,autor_carte,genul,editura,nr_carti_disponibile from bibl;");
        ResultSet rs = pst.executeQuery() ;
        int x,y;
        ResultSetMetaData data = rs.getMetaData();
        y = data.getColumnCount();
        
        DefaultTableModel tableRecords = (DefaultTableModel)jTable1.getModel();
        tableRecords.setRowCount(0);
        
        while(rs.next()){
            Vector columnData = new Vector();
            for(x=1; x<=y; x++){
                String nume=rs.getString("nume_carte");
                columnData.add(nume);
                columnData.add(rs.getString("autor_carte"));
                columnData.add(rs.getString("genul"));
                columnData.add(rs.getString("editura"));
                int z =rs.getInt("nr_carti_disponibile");
                if (z!=0){columnData.add(z);
                columnData.add("Disponibil!");
                }else{columnData.add(z);
                PreparedStatement pst1 =con.prepareStatement("Select Min(Data_restituirii) from imprumut where Numele_cartii_imprumutate=? and Restituit=0;");
                pst1.setString(1, nume);
                ResultSet rs1 = pst1.executeQuery() ;
                rs1.next();
                columnData.add(rs1.getString("Min(Data_restituirii)"));    
                }
            }
            tableRecords.addRow(columnData);
        }
        }catch(Exception e){
         
        }
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
                    ModerMenu men = new ModerMenu();
                    men.setVisible(true);
                    setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insActionPerformed
        if (t.getText().equals(""))JOptionPane.showMessageDialog(null, "Completati campul 'Titlu'!");
        else if (a.getText().equals(""))JOptionPane.showMessageDialog(null, "Completati campul 'Autor'!");
        else if (g.getText().equals(""))JOptionPane.showMessageDialog(null, "Completati campul 'Genul'!");
        else if (e.getText().equals(""))JOptionPane.showMessageDialog(null, "Completati campul 'Editura'!");
        else try{
            if (nr.getText().equals(""))JOptionPane.showMessageDialog(null, "Completati campul 'Numarul de carti'!");
            else{
            if (Integer.parseInt(nr.getText())<1)JOptionPane.showMessageDialog(null, "Numarul de carti este mai mic ca 1!");
            else{
            try{
            Connection con=BDConn.getBDConn();
            PreparedStatement pst =con.prepareStatement("Select Count(nume_carte) from bibl where nume_carte=?");
            pst.setString(1, t.getText());
            ResultSet rs = pst.executeQuery();
            rs.next();
            System.out.println(rs.getInt("Count(nume_carte)"));
            if (rs.getInt("Count(nume_carte)")==0){
            String sql =("INSERT INTO bibl (nume_carte, autor_carte, genul,editura,nr_carti,nr_carti_disponibile) VALUES (?, ?, ?,?,?,?)");
            pst = con.prepareStatement(sql);
            pst.setString(1, t.getText());
            pst.setString(2, a.getText());
            pst.setString(3, g.getText());
            pst.setString(4, e.getText());
            pst.setString(5, nr.getText());
            pst.setString(6, nr.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cartea a fost adaugata cu succes!");
            showTableData();
            t.setText("");
            a.setText("");
            g.setText("");
            e.setText("");
            nr.setText("");
            
            }else{
              JOptionPane.showMessageDialog(null, "Cartea este in biblioteca!");  
            }}catch(Exception e){
              JOptionPane.showMessageDialog(null, "Error apelati adminul!");
            }}
            
            }}catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ati folosit alte caractere decat cifre pentru nr de carti!");
        }
        
    }//GEN-LAST:event_insActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JButton back;
    private javax.swing.JTextField e;
    private javax.swing.JButton exit;
    private javax.swing.JTextField g;
    private javax.swing.JButton ins;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nr;
    private javax.swing.JTextField t;
    private javax.swing.JLabel textUser1;
    private javax.swing.JLabel textUser2;
    private javax.swing.JLabel textUser3;
    private javax.swing.JLabel textUser4;
    private javax.swing.JLabel textUser5;
    // End of variables declaration//GEN-END:variables
}
